### Generate Wallet
POST http://localhost:5000/api/v1/wallets/generate
Content-Type: application/json


### Update Multisig Permissions
POST http://localhost:5000/api/v1/wallets/update-permission
Content-Type: application/json

{
    "walletId": "6891ef23a561bde570f8e60a"
}

### Get TRX Balance
GET http://localhost:5000/api/v1/wallets/balance/trx/TYXZiS92bv4Mvu63rNBn8SPTU22tURgTAu

### Get TRC20 Token Balance
GET http://localhost:5000/api/v1/wallets/balance/trc20/TYXZiS92bv4Mvu63rNBn8SPTU22tURgTAu/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

### Register User
POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
    "username": "prof01",
    "password": "0240119926@CoinsKart"
}

### Login User
POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
    "username": "prof01",
    "password": "0240119926@CoinsKart"
}

### Logout User
POST http://localhost:5000/api/v1/users/logout

### Delete User
DELETE http://localhost:5000/api/v1/users/688f12052564638c02205453

### Get All Users
GET http://localhost:5000/api/v1/users

### Get All Sweep Logs
GET http://localhost:5000/api/v1/sweep-logs

### Get All Transaction Logs
GET http://localhost:5000/api/v1/transaction-logs

### Get User By ID
GET http://localhost:5000/api/v1/users/688f12052564638c02205453

### Get All Wallets
GET http://localhost:5000/api/v1/wallets

### Delete Wallet
DELETE http://localhost:5000/api/v1/wallets/688db9b79b8b8f89cd00f394

### Get All Single Wallets
GET http://localhost:5000/api/v1/single-wallets

### Generate Single Wallet
POST http://localhost:5000/api/v1/single-wallets/generate
Content-Type: application/json

{}

### Delete Single Wallet
DELETE http://localhost:5000/api/v1/single-wallets/6891ff2e9fbeff02abe57f0b

### Send TRX from Single Wallet
POST http://localhost:5000/api/v1/single-wallets/trx
Content-Type: application/json

{
    "walletId": "6891ff359fbeff02abe57f0e",
    "toAddress": "THAL1TgD3uDbKUS5eQwW96HLPDZVbPVANK",
    "amount": 10
}

### Send TRX from Multisig Wallet
POST http://localhost:5000/api/v1/withdraw/trx
Content-Type: application/json

{
    "walletId": "6891ef23a561bde570f8e60a",
    "toAddress": "THAL1TgD3uDbKUS5eQwW96HLPDZVbPVANK",
    "amount": 10
}

### Send TRC20 Token from Single Wallet
POST http://localhost:5000/api/v1/single-wallets/trc20
Content-Type: application/json

{
    "walletId": "6891ff359fbeff02abe57f0e",
    "toAddress": "THAL1TgD3uDbKUS5eQwW96HLPDZVbPVANK",
    "amount": 100,
    "tokenContractAddress": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
}

### Get User
GET http://localhost:5000/api/v1/users/user/dashboard

### Get Wallet By ID
GET http://localhost:5000/api/v1/wallets/688db2cd0d0329746cc8e0c0                    